#logging:
#  level.: INFO

server:
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    initialize: true
    schema: classpath*:database/init.sql
    data: classpath*:database/insert.sql
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:student_management;DB_CLOSE_DELAY=-1
    username: sa
    password: sa

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    show-sql: true

  messages:
    basename: messages
    encoding: UTF-8
    use-code-as-default-message: true

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
