CREATE TABLE IF NOT EXISTS groups (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(8) NOT NULL,
    faculty_name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS students(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    l_name VARCHAR(45) NOT NULL,
    f_name VARCHAR(45) NOT NULL,
    m_name VARCHAR(45),
    dob DATE NOT NULL,
    group_id BIGINT NOT NULL,
    CONSTRAINT FK_STUDENTS_GROUP_ID FOREIGN KEY(group_id) REFERENCES groups(id)
);